/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.4
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00 
 *
 * The version of the OpenAPI document: 1.5.4
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    updated_at?: string;
    /**
     * The object class to which the attachment must be linked.
     * @type {string}
     * @memberof Attachment
     */
    attachable_type: AttachmentAttachableTypeEnum;
    /**
     * ID of the model this attachment is linked to.
     * @type {string}
     * @memberof Attachment
     */
    attachable_id: string;
    /**
     * MD5 hash of the file for basic duplicate detection.
     * @type {string}
     * @memberof Attachment
     */
    md5?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    download_url?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    upload_url?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    size?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum AttachmentAttachableTypeEnum {
    Account = 'Account',
    Budget = 'Budget',
    Bill = 'Bill',
    TransactionJournal = 'TransactionJournal',
    PiggyBank = 'PiggyBank',
    Tag = 'Tag'
}



