/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BillPaidDates } from './bill-paid-dates';
import { BillRepeatFrequency } from './bill-repeat-frequency';

/**
 * 
 * @export
 * @interface Bill
 */
export interface Bill {
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    updated_at?: string;
    /**
     * Use either currency_id or currency_code
     * @type {string}
     * @memberof Bill
     */
    currency_id?: string;
    /**
     * Use either currency_id or currency_code
     * @type {string}
     * @memberof Bill
     */
    currency_code?: string;
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    currency_symbol?: string;
    /**
     * 
     * @type {number}
     * @memberof Bill
     */
    currency_decimal_places?: number;
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    amount_min: string;
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    amount_max: string;
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    date: string;
    /**
     * The date after which this bill is no longer valid or applicable
     * @type {string}
     * @memberof Bill
     */
    end_date?: string;
    /**
     * The date before which the bill must be renewed (or cancelled)
     * @type {string}
     * @memberof Bill
     */
    extension_date?: string;
    /**
     * 
     * @type {BillRepeatFrequency}
     * @memberof Bill
     */
    repeat_freq: BillRepeatFrequency;
    /**
     * How often the bill must be skipped. 1 means a bi-monthly bill.
     * @type {number}
     * @memberof Bill
     */
    skip?: number;
    /**
     * If the bill is active.
     * @type {boolean}
     * @memberof Bill
     */
    active?: boolean;
    /**
     * Order of the bill.
     * @type {number}
     * @memberof Bill
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof Bill
     */
    notes?: string | null;
    /**
     * When the bill is expected to be due.
     * @type {string}
     * @memberof Bill
     */
    next_expected_match?: string | null;
    /**
     * Formatted (locally) when the bill is due.
     * @type {string}
     * @memberof Bill
     */
    next_expected_match_diff?: string | null;
    /**
     * The group ID of the group this object is part of. NULL if no group.
     * @type {string}
     * @memberof Bill
     */
    object_group_id?: string | null;
    /**
     * The order of the group. At least 1, for the highest sorting.
     * @type {number}
     * @memberof Bill
     */
    object_group_order?: number | null;
    /**
     * The name of the group. NULL if no group.
     * @type {string}
     * @memberof Bill
     */
    object_group_title?: string | null;
    /**
     * Array of future dates when the bill is expected to be paid. Autogenerated.
     * @type {Array<string>}
     * @memberof Bill
     */
    pay_dates?: Array<string>;
    /**
     * Array of past transactions when the bill was paid.
     * @type {Array<BillPaidDates>}
     * @memberof Bill
     */
    paid_dates?: Array<BillPaidDates>;
}


