/* tslint:disable */
/* eslint-disable */
/**
 * Firefly III API v1.5.6
 * This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2022-04-04T03:54:41+00:00 
 *
 * The version of the OpenAPI document: 1.5.6
 * Contact: james@firefly-iii.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebhookAttempt
 */
export interface WebhookAttempt {
    /**
     * 
     * @type {string}
     * @memberof WebhookAttempt
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookAttempt
     */
    updated_at?: string;
    /**
     * The ID of the webhook message this attempt belongs to.
     * @type {string}
     * @memberof WebhookAttempt
     */
    webhook_message_id?: string;
    /**
     * The HTTP status code of the error, if any.
     * @type {number}
     * @memberof WebhookAttempt
     */
    status_code?: number | null;
    /**
     * Internal log for this attempt. May contain sensitive user data.
     * @type {string}
     * @memberof WebhookAttempt
     */
    logs?: string | null;
    /**
     * Webhook receiver response for this attempt, if any. May contain sensitive user data.
     * @type {string}
     * @memberof WebhookAttempt
     */
    response?: string | null;
}


